---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wmbusmeters-prometheus-metric
  namespace: kube-system
  labels:
    app: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exporter
  template:
    metadata:
      labels:
        app: exporter
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9001"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: wmbusmeters-prometheus-metric
        image: medinvention/wmbusmeters-prometheus-metric:0.0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9001
          initialDelaySeconds: 15
          periodSeconds: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: wmbusmeters-prometheus-metric
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 9001
    targetPort: 9001
  selector:
    app: exporter