{
 "title": "Home",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total water usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(water_cubic_used{name=\"HotWater\"})",
     "legendFormat": "Hot"
    },
    {
     "expr": "max(water_cubic_used{name=\"ColdWater\"})",
     "legendFormat": "Cold"
    }
   ]
  },
  {
   "title": "Total Heat usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(heat_cubic_consumption)", "legendFormat": "Cubic" },
    { "expr": "max(heat_kwh_consumption)", "legendFormat": "KWH" }
   ]
  },
  {
   "title": "Heat Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(last_over_time(heat_cubic_flow[$__interval]))",
     "legendFormat": "Flow cubic"
    },
    {
     "expr": "avg(last_over_time(heat_kwh_flow[$__interval]))",
     "legendFormat": "Flow KWH"
    },
    {
     "expr": "heat_temperature_flow - heat_temperature_return",
     "legendFormat": "Spend"
    }
   ]
  },
  { "title": "Consumption by day", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Hot Water consumption by day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "expr": "max_over_time(water_cubic_used{name=\"HotWater\"}[1d]) - min_over_time(water_cubic_used{name=\"HotWater\"}[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cold Water consumption by day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "expr": "max_over_time(water_cubic_used{name=\"ColdWater\"}[1d]) - min_over_time(water_cubic_used{name=\"ColdWater\"}[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heat cubic consumption by day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "max_over_time(heat_kwh_consumption[1d]) - min_over_time(heat_kwh_consumption[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heat cubic consumption by day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "expr": "max_over_time(heat_cubic_consumption[1d]) - min_over_time(heat_cubic_consumption[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cold Water History",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "targets": [
      {
       "expr": "avg(water_cubic_used{name=\"ColdWater\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Hot Water History",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "targets": [
      {
       "expr": "avg(water_cubic_used{name=\"HotWater\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Heat History",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "targets": [
      { "expr": "avg(heat_cubic_consumption)", "legendFormat": "{{name}}" }
     ]
    }
   ]
  }
 ]
}